#!/usr/bin/python3

import signal
from sys import argv
from math import sqrt


def handler(signum, frame):
    print("Error: Time limit exceeded")
    exit(1)


def factor():
    signal.signal(signal.SIGALRM, handler)
    signal.alarm(5)
    with open(argv[1]) as f:
        for line in f:
            line = line.strip()
            try:
                num = int(line)
            except ValueError:
                continue
            if num % 2 == 0:
                p = 2
                q = num // 2
            else:
                sqn = int(sqrt(num))
                if sqn % 2 == 0:
                    sqn += 1
                for i in range(3, sqn + 1, 2):
                    if num % i == 0:
                        p = i
                        q = num // i
                        break
                if num % i != 0:
                    p = num
                    q = 1
            print("{} = {} * {}".format(num, p, q))
    signal.alarm(0)


factor()
